// Zone 4 — Emberfall Reach (levels 20-26). The first zone past the shipped 1-20 game
// and the first step toward the 1-60 vision. Continues the Gravecaller saga: Korzul the
// Gravewyrm died at level 20 (zone 3), but his necrotic death-fire took root in the
// volcanic slopes beyond Thornpeak. A cult remnant, the Emberbound, now worship the fire.
//
// Design: docs/studio/gdd/zone4-emberfall-reach.md. Follows the master-spec method
// (hpBase ~= 40 + 18*level, kill XP 45+5*mobLevel, quest XP <= 25% of the at-level need,
// three-archetype rewards). All names/text/coords original; reuses existing mob affixes
// only (no new sim mechanic). Biome reuses 'peaks' (no renderer work this pass).

import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../types';

export const ZONE4_ZONE: ZoneDef = {
  id: 'emberfall_reach',
  name: 'Emberfall Reach',
  zMin: 900,
  zMax: 1260,
  levelRange: [20, 26],
  biome: 'peaks',
  hub: { x: 0, z: 980, radius: 20, name: 'Cinderhold' },
  graveyard: { x: 14, z: 965 },
  // "lakes" double as lava pools in this band (same field, reused as-is).
  lakes: [
    { x: -60, z: 1060, radius: 16 }, // The Slagmere
    { x: 90, z: 1140, radius: 12 }, // The Cinderpit
  ],
  pois: [
    { x: 0, z: 980, label: 'Cinderhold' },
    { x: -55, z: 1010, label: 'Ashclaw Scrub' },
    { x: 70, z: 1030, label: 'Cindermarch Tunnels' },
    { x: -90, z: 1070, label: 'The Slagmere' },
    { x: 50, z: 1080, label: 'Charwing Roost' },
    { x: -40, z: 1120, label: 'Blightash Flats' },
    { x: 100, z: 1110, label: "Slagjaw's Hold" },
    { x: 0, z: 1160, label: 'Emberbound Camp' },
    { x: -20, z: 1200, label: 'The Cinderpit' },
    { x: 0, z: 1240, label: 'The Emberward Vault' },
  ],
  welcome: 'Warden Ulra holds the line at Cinderhold, against fire that should have died with the Wyrm.',
};

// Mountain road continuing from the Gravewyrm Sanctum (0,880) into the ember frontier.
export const ZONE4_ROADS: { x: number; z: number }[][] = [
  [
    { x: 0, z: 880 },
    { x: 0, z: 940 },
    { x: 0, z: 980 },
  ], // Sanctum -> Cinderhold
  [
    { x: -6, z: 986 },
    { x: -40, z: 1000 },
    { x: -60, z: 1015 },
  ], // -> Ashclaw Scrub
  [
    { x: 6, z: 988 },
    { x: 50, z: 1010 },
    { x: 75, z: 1032 },
  ], // -> Cindermarch Tunnels
  [
    { x: 0, z: 996 },
    { x: 0, z: 1080 },
    { x: 0, z: 1160 },
    { x: 0, z: 1240 },
  ], // -> Emberbound Camp -> Cinderpit -> Vault
];

// ---------------------------------------------------------------------------
// Mobs (overworld only — the Emberward Vault mobs live in content/dungeons)
// ---------------------------------------------------------------------------

export const ZONE4_MOBS: Record<string, MobTemplate> = {
  ashclaw_warg: {
    id: 'ashclaw_warg',
    name: 'Ashclaw Warg',
    minLevel: 20,
    maxLevel: 21,
    family: 'beast',
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 8.2,
    aggroRadius: 11,
    bleed: { chance: 0.25, perTick: 6, interval: 3, duration: 9, name: 'Ash-Rend', school: 'physical' },
    loot: [
      { copper: 95, chance: 1 },
      { itemId: 'ashclaw_pelt', chance: 0.6, questId: 'q_ashclaw_pelts' },
    ],
    scale: 0.95,
    color: 0x6b5a4a,
  },
  // The pack father: a scarred old warg that rallies its kin with a dying howl.
  ashclaw_alpha: {
    id: 'ashclaw_alpha',
    name: 'Ashclaw Alpha',
    minLevel: 21,
    maxLevel: 21,
    family: 'beast',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 380,
    hpPerLevel: 64,
    dmgBase: 17,
    dmgPerLevel: 3.4,
    attackSpeed: 1.9,
    armorPerLevel: 24,
    moveSpeed: 8.8,
    aggroRadius: 13,
    packFrenzy: { radius: 14, hasteMult: 1.3, duration: 8 },
    enrage: { belowHpPct: 0.35, dmgMult: 1.4, hasteMult: 1.3 },
    loot: [
      { copper: 550, chance: 1 },
      { itemId: 'alphas_fang', chance: 1, questId: 'q_ashclaw_alpha' },
      { itemId: 'alphas_fang_mantle', chance: 0.3 },
    ],
    scale: 1.3,
    color: 0x5a4a3a,
  },
  cindermarch_kobold: {
    id: 'cindermarch_kobold',
    name: 'Cindermarch Stoker',
    minLevel: 21,
    maxLevel: 22,
    family: 'kobold',
    hpBase: 74,
    hpPerLevel: 25,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7.6,
    aggroRadius: 11,
    cinder: { chance: 0.3, perTick: 5, interval: 3, duration: 9, name: 'Stoked Coals', school: 'fire' },
    loot: [
      { copper: 100, chance: 1 },
      { itemId: 'cinder_resin', chance: 0.5, questId: 'q_cinder_resin' },
    ],
    scale: 0.85,
    color: 0x8a6a3a,
  },
  cindermarch_blaster: {
    id: 'cindermarch_blaster',
    name: 'Cindermarch Blaster',
    minLevel: 22,
    maxLevel: 22,
    family: 'kobold',
    elite: true,
    hpBase: 130,
    hpPerLevel: 30,
    dmgBase: 16,
    dmgPerLevel: 3.1,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7.6,
    aggroRadius: 12,
    aoePulse: { min: 18, max: 26, radius: 7, every: 9, name: 'Powder Cask', school: 'fire', fx: 'nova' },
    loot: [{ copper: 240, chance: 1 }],
    scale: 1.0,
    color: 0x9a5a2a,
  },
  emberbound_initiate: {
    id: 'emberbound_initiate',
    name: 'Emberbound Initiate',
    minLevel: 22,
    maxLevel: 23,
    family: 'humanoid',
    hpBase: 78,
    hpPerLevel: 25,
    dmgBase: 15,
    dmgPerLevel: 3.0,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7.5,
    aggroRadius: 11,
    loot: [
      { copper: 110, chance: 1 },
      { itemId: 'emberbound_orders', chance: 0.5, questId: 'q_emberbound_orders' },
    ],
    scale: 1.0,
    color: 0xb04020,
  },
  emberbound_pyromancer: {
    id: 'emberbound_pyromancer',
    name: 'Emberbound Pyromancer',
    minLevel: 23,
    maxLevel: 23,
    family: 'humanoid',
    hpBase: 76,
    hpPerLevel: 25,
    dmgBase: 16,
    dmgPerLevel: 3.1,
    attackSpeed: 2.0,
    armorPerLevel: 15,
    moveSpeed: 7.5,
    aggroRadius: 12,
    smolder: { chance: 0.3, perTick: 6, interval: 3, duration: 9, name: 'Searing Brand', school: 'fire' },
    spellVuln: { chance: 0.25, amp: 0.15, duration: 12, name: 'Brand of Embers', school: 'fire' },
    loot: [{ copper: 120, chance: 1 }],
    scale: 1.0,
    color: 0xc83018,
  },
  blightash_revenant: {
    id: 'blightash_revenant',
    name: 'Blightash Revenant',
    minLevel: 23,
    maxLevel: 24,
    family: 'undead',
    hpBase: 82,
    hpPerLevel: 26,
    dmgBase: 16,
    dmgPerLevel: 3.1,
    attackSpeed: 2.3,
    armorPerLevel: 17,
    moveSpeed: 7.4,
    aggroRadius: 11,
    soulrot: { chance: 0.25, perTick: 6, interval: 3, duration: 9, name: 'Cinder Rot', school: 'shadow' },
    loot: [
      { copper: 130, chance: 1 },
      { itemId: 'ash_bound_remains', chance: 0.4 },
    ],
    scale: 1.05,
    color: 0x4a3a30,
  },
  blightash_wight: {
    id: 'blightash_wight',
    name: 'Blightash Wight',
    minLevel: 24,
    maxLevel: 24,
    family: 'undead',
    elite: true,
    hpBase: 150,
    hpPerLevel: 32,
    dmgBase: 18,
    dmgPerLevel: 3.3,
    attackSpeed: 2.2,
    armorPerLevel: 19,
    moveSpeed: 7.4,
    aggroRadius: 12,
    enervate: { chance: 0.3, sta: 14, duration: 12, name: 'Withering Ash', school: 'shadow' },
    loot: [
      { copper: 280, chance: 1 },
      { itemId: 'wight_ash_locket', chance: 0.5, questId: 'q_blightash_wights' },
    ],
    scale: 1.1,
    color: 0x3a2e28,
  },
  charwing_roc: {
    id: 'charwing_roc',
    name: 'Charwing Roc',
    minLevel: 24,
    maxLevel: 24,
    family: 'beast',
    hpBase: 86,
    hpPerLevel: 27,
    dmgBase: 17,
    dmgPerLevel: 3.2,
    attackSpeed: 1.9,
    armorPerLevel: 17,
    moveSpeed: 8.6,
    aggroRadius: 12,
    cleave: { radius: 6, mult: 0.6, name: 'Talon Sweep' },
    loot: [
      { copper: 140, chance: 1 },
      { itemId: 'charwing_egg', chance: 0.5, questId: 'q_charwing_eggs' },
    ],
    scale: 1.1,
    color: 0x7a3a1a,
  },
  charwing_matriarch: {
    id: 'charwing_matriarch',
    name: 'Charwing Matriarch',
    minLevel: 25,
    maxLevel: 25,
    family: 'beast',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 520,
    hpPerLevel: 82,
    dmgBase: 22,
    dmgPerLevel: 4.0,
    attackSpeed: 1.8,
    armorPerLevel: 26,
    moveSpeed: 8.8,
    aggroRadius: 13,
    aoePulse: { min: 24, max: 34, radius: 9, every: 10, name: 'Cinder Dive', school: 'fire', fx: 'nova' },
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.3 },
    loot: [
      { copper: 650, chance: 1 },
      { itemId: 'matriarchs_talon', chance: 1, questId: 'q_charwing_matriarch' },
      { itemId: 'matriarchs_crest_helm', chance: 0.3 },
    ],
    scale: 1.35,
    color: 0x8a2a10,
  },
  slagjaw_marauder: {
    id: 'slagjaw_marauder',
    name: 'Slagjaw Marauder',
    minLevel: 24,
    maxLevel: 25,
    family: 'ogre',
    hpBase: 90,
    hpPerLevel: 27,
    dmgBase: 18,
    dmgPerLevel: 3.2,
    attackSpeed: 2.6,
    armorPerLevel: 18,
    moveSpeed: 7.6,
    aggroRadius: 11,
    staggerHit: { chance: 0.3, dodgeReduction: 0.05, duration: 8, name: 'Brutal Cuff' },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'slagjaw_brand', chance: 0.5, questId: 'q_slagjaw_raiders' },
    ],
    scale: 1.3,
    color: 0x6a5a3a,
  },
  slagjaw_chieftain: {
    id: 'slagjaw_chieftain',
    name: 'Slagjaw Chieftain',
    minLevel: 25,
    maxLevel: 25,
    family: 'ogre',
    elite: true,
    boss: true,
    hpBase: 320,
    hpPerLevel: 40,
    dmgBase: 21,
    dmgPerLevel: 3.6,
    attackSpeed: 2.7,
    armorPerLevel: 22,
    moveSpeed: 7.6,
    aggroRadius: 12,
    rampage: { ap: 24, maxStacks: 5, duration: 10, name: 'Molten Fury' },
    loot: [
      { copper: 3200, chance: 1 },
      { itemId: 'slagjaw_warhelm', chance: 0.3 },
    ],
    scale: 1.55,
    color: 0x7a4a2a,
  },
  magma_husk: {
    id: 'magma_husk',
    name: 'Magma Husk',
    minLevel: 25,
    maxLevel: 26,
    family: 'elemental',
    hpBase: 96,
    hpPerLevel: 28,
    dmgBase: 19,
    dmgPerLevel: 3.3,
    attackSpeed: 2.2,
    armorPerLevel: 18,
    moveSpeed: 6.6,
    aggroRadius: 11,
    smolder: { chance: 0.3, perTick: 7, interval: 3, duration: 9, name: 'Slag Splash', school: 'fire' },
    loot: [
      { copper: 170, chance: 1 },
      { itemId: 'cooling_slag_core', chance: 0.5, questId: 'q_emberash_cores' },
    ],
    scale: 1.15,
    color: 0xc4501a,
  },
  ember_wisp: {
    id: 'ember_wisp',
    name: 'Ember Wisp',
    minLevel: 25,
    maxLevel: 25,
    family: 'elemental',
    hpBase: 80,
    hpPerLevel: 26,
    dmgBase: 17,
    dmgPerLevel: 3.1,
    attackSpeed: 2.4,
    armorPerLevel: 14,
    moveSpeed: 8.4,
    aggroRadius: 12,
    manaBurn: { chance: 0.3, amount: 90, name: 'Searing Drain', school: 'fire' },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'ember_wisp_core', chance: 0.5, questId: 'q_emberward_wisps' },
    ],
    scale: 0.9,
    color: 0xff7a2a,
  },
  vrask_the_emberseer: {
    id: 'vrask_the_emberseer',
    name: 'Vrask the Emberseer',
    minLevel: 26,
    maxLevel: 26,
    family: 'humanoid',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 560,
    hpPerLevel: 88,
    dmgBase: 23,
    dmgPerLevel: 4.0,
    attackSpeed: 2.1,
    armorPerLevel: 24,
    moveSpeed: 7.5,
    aggroRadius: 13,
    mendAlly: {
      healMin: 50,
      healMax: 74,
      radius: 14,
      every: 7,
      name: 'Ember Benediction',
      school: 'fire',
    },
    aoePulse: { min: 22, max: 32, radius: 8, every: 10, name: 'Cinder Bolt', school: 'fire', fx: 'projectile' },
    loot: [
      { copper: 800, chance: 1 },
      { itemId: 'vrasks_emberstaff', chance: 1, questId: 'q_vrask' },
    ],
    scale: 1.2,
    color: 0xd14820,
  },
};

// ---------------------------------------------------------------------------
// Hub NPCs (Cinderhold)
// ---------------------------------------------------------------------------

export const ZONE4_NPCS: Record<string, NpcDef> = {
  warden_ulra: {
    id: 'warden_ulra',
    name: 'Warden Ulra',
    title: 'Cinderhold Warden',
    pos: { x: 4, z: 984 },
    facing: -2.0,
    color: 0x9a7a5a,
    questIds: [
      'q_cinderhold_signal',
      'q_ashclaw_culling',
      'q_cindermarch_tunnels',
      'q_cindermarch_blasters',
      'q_slagjaw_raiders',
      'q_slagjaw_chieftain',
    ],
    greeting:
      'The Wyrm is dead, $C, and still this fire will not die with it. Hold the line at Cinderhold, and we may yet smother it.',
  },
  brother_aldric_cinderhold: {
    id: 'brother_aldric_cinderhold',
    name: 'Brother Aldric',
    title: 'Priest of the Vale',
    pos: { x: -10, z: 976 },
    facing: 0.8,
    color: 0xf7f9f9,
    questIds: [
      'q_cinderhold_signal',
      'q_emberbound_scouts',
      'q_emberbound_orders',
      'q_blightash_unrest',
      'q_blightash_wights',
      'q_emberward_signal',
      'q_emberward_wisps',
      'q_grand_pyrist',
      'q_korzuls_ember',
      'q_the_emberward_vault',
    ],
    greeting:
      'I stood over Korzul as it died, $N. I thought that the end. But the fire it bled into the rock still creeps — and now there are those who would feed it.',
  },
  scout_brannis: {
    id: 'scout_brannis',
    name: 'Scout Brannis',
    title: 'Frontier Tracker',
    pos: { x: 7, z: 990 },
    facing: -2.4,
    color: 0x7a8a6a,
    questIds: ['q_ashclaw_alpha', 'q_charwing_eggs', 'q_charwing_matriarch'],
    greeting: 'Every track on this frontier ends at the same place, $N: the fire. Mind your step.',
  },
  quartermaster_dessa: {
    id: 'quartermaster_dessa',
    name: 'Quartermaster Dessa',
    title: 'Cinderhold Quartermaster',
    pos: { x: -5, z: 988 },
    facing: 1.6,
    color: 0xa08868,
    questIds: ['q_ashclaw_pelts', 'q_cinder_resin'],
    vendorItems: [
      'cinderhold_hardbread',
      'cinderwater_flask',
      'slagmere_broth',
      'ashveil_cider',
      'cinderhold_breastplate',
      'ashveil_robe',
      'cinderscale_jerkin',
      'slagtread_boots',
      'emberward_leggings',
    ],
    greeting: 'Mountain stores for a mountain that is on fire, $N. Take what you need.',
  },
  armorer_kovan: {
    id: 'armorer_kovan',
    name: 'Armorer Kovan',
    title: 'Cinderhold Armorer',
    pos: { x: -2, z: 992 },
    facing: 2.8,
    color: 0x8a7a6a,
    questIds: [],
    vendorItems: ['cinderhold_warblade', 'slagforge_staff', 'ashfall_dirk'],
    greeting: 'Slag-forged steel, $N. It has already been through worse fire than you will face.',
  },
  loremaster_sela: {
    id: 'loremaster_sela',
    name: 'Loremaster Sela',
    title: 'Cinderhold Loremaster',
    pos: { x: 12, z: 975 },
    facing: -1.2,
    color: 0xc0b0a0,
    questIds: ['q_emberash_study', 'q_emberash_cores', 'q_vrask'],
    greeting:
      'The fire is not natural, $N. It remembers. Help me learn what it remembers, and we may learn how to make it forget.',
  },
};

// ---------------------------------------------------------------------------
// Quests
// ---------------------------------------------------------------------------

export const ZONE4_QUESTS: Record<string, QuestDef> = {
  q_cinderhold_signal: {
    id: 'q_cinderhold_signal',
    name: 'The Line at Cinderhold',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'warden_ulra',
    text: "Korzul is dead, $N, but its death-fire crept past Thornpeak and surfaced here. Warden Ulra holds a half-built waystation against it. A signal flare stands at the Cinderhold gate — take it up, and tell her the priest of the Vale stands with her.",
    completionText: 'If Aldric vouches for you, that is enough for me. Welcome to the Reach, $N. It is not much, but it is the line.',
    objectives: [
      { type: 'collect', itemId: 'cinderhold_signal_flare', count: 1, label: 'Cinderhold Signal Flare' },
    ],
    xpReward: 1200,
    copperReward: 600,
    itemRewards: {},
    minLevel: 20,
  },
  q_ashclaw_culling: {
    id: 'q_ashclaw_culling',
    name: 'Wargs on the Ash',
    giverNpcId: 'warden_ulra',
    turnInNpcId: 'warden_ulra',
    text: 'The wargs of the Ashclaw Scrub have grown bold and many, driven down from the burning slopes. Thin them, $N — twelve, to keep the road south of the hold open.',
    completionText: 'Twelve fewer shadows on the ash. The supply road breathes easier.',
    objectives: [{ type: 'kill', targetMobId: 'ashclaw_warg', count: 12, label: 'Ashclaw Warg slain' }],
    xpReward: 3600,
    copperReward: 1500,
    itemRewards: {},
  },
  q_ashclaw_pelts: {
    id: 'q_ashclaw_pelts',
    name: 'Ash-Cured Leather',
    giverNpcId: 'quartermaster_dessa',
    turnInNpcId: 'quartermaster_dessa',
    text: 'Warg hide cured in ash takes a heat-ward no tannery can match, $N. Bring me eight Ashclaw pelts and I will line the watch with something that does not catch fire.',
    completionText: 'Eight good hides. The watch will not burn this season — take these treads for your trouble.',
    objectives: [{ type: 'collect', itemId: 'ashclaw_pelt', count: 8, label: 'Ashclaw Pelt' }],
    xpReward: 3700,
    copperReward: 1500,
    itemRewards: { warrior: 'ashclaw_treads', mage: 'ashclaw_treads', rogue: 'ashclaw_treads' },
  },
  q_ashclaw_alpha: {
    id: 'q_ashclaw_alpha',
    name: 'The Pack Father',
    giverNpcId: 'scout_brannis',
    turnInNpcId: 'scout_brannis',
    text: 'One old warg leads them all — a scarred grey brute the trackers call the Alpha. Kill the pack father and the rest will scatter. It prowls the western edge of the Scrub. Bring me its fang.',
    completionText: "The pack father's fang. The Scrub will be quiet for a while now. This mantle is yours, $N — warg-leather, ash-cured.",
    objectives: [{ type: 'collect', itemId: 'alphas_fang', count: 1, label: "Alpha's Fang" }],
    xpReward: 4200,
    copperReward: 2000,
    itemRewards: { warrior: 'alphas_fang_mantle', mage: 'alphas_fang_mantle', rogue: 'alphas_fang_mantle' },
    minLevel: 21,
  },
  q_cindermarch_tunnels: {
    id: 'q_cindermarch_tunnels',
    name: 'Trouble in the Cindermarch',
    giverNpcId: 'warden_ulra',
    turnInNpcId: 'warden_ulra',
    text: 'The kobolds of the Cindermarch Tunnels mine the seep itself, hauling out coals that should never have been lit. Kill twelve Cindermarch Stokers before they dig something loose.',
    completionText: 'Stoking the fire is exactly what we do not need. Well done thinning them, $N.',
    objectives: [{ type: 'kill', targetMobId: 'cindermarch_kobold', count: 12, label: 'Cindermarch Stoker slain' }],
    xpReward: 4000,
    copperReward: 1700,
    itemRewards: {},
    minLevel: 21,
  },
  q_cinder_resin: {
    id: 'q_cinder_resin',
    name: 'Sticky Business',
    giverNpcId: 'quartermaster_dessa',
    turnInNpcId: 'quartermaster_dessa',
    text: 'The Stokers pack their casks with cinder resin — a tar that smothers flame as well as it feeds it. Bring me six wads of it from the tunnels and I will ward the hold gates.',
    completionText: 'Six wads of resin. The gates will hold against an ember storm now.',
    objectives: [{ type: 'collect', itemId: 'cinder_resin', count: 6, label: 'Cinder Resin' }],
    xpReward: 4100,
    copperReward: 1700,
    itemRewards: {},
    requiresQuest: 'q_cindermarch_tunnels',
  },
  q_cindermarch_blasters: {
    id: 'q_cindermarch_blasters',
    name: 'Powder Casks',
    giverNpcId: 'warden_ulra',
    turnInNpcId: 'warden_ulra',
    text: 'The deepest Cindermarch kobolds carry powder casks — Blasters, the trackers call them, and they go up like the mountain itself. Ten of them, $N, before they bring a tunnel down on the road. Take a partner.',
    completionText: 'Ten casks defused the hard way. The tunnels will not collapse the road this week.',
    objectives: [{ type: 'kill', targetMobId: 'cindermarch_blaster', count: 10, label: 'Cindermarch Blaster slain' }],
    xpReward: 5000,
    copperReward: 2400,
    itemRewards: {},
    minLevel: 22,
    suggestedPlayers: 2,
  },
  q_emberbound_scouts: {
    id: 'q_emberbound_scouts',
    name: 'Chants in the Ash',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'I know those chants, $N. The Emberbound are Wyrmcult, the same sect we broke at the Sanctum — only now they worship the fire itself. Their initiates muster at the Emberbound Camp to the south. Cut down twelve before they become something worse.',
    completionText: 'The same prayers, twisted toward the flame. They did not die with their god, $N. They merely chose a new one.',
    objectives: [{ type: 'kill', targetMobId: 'emberbound_initiate', count: 12, label: 'Emberbound Initiate slain' }],
    xpReward: 4800,
    copperReward: 2200,
    itemRewards: {},
    minLevel: 22,
  },
  q_emberbound_orders: {
    id: 'q_emberbound_orders',
    name: 'Orders from the Embers',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'The initiates carry written orders, $N. Kill eight more and bring me four sets — I would know what the Emberbound are building before they finish building it.',
    completionText: 'An "ember heart," the orders call it — something to make the blight permanent. We must reach their vault before the rite is done.',
    objectives: [
      { type: 'kill', targetMobId: 'emberbound_initiate', count: 8, label: 'Emberbound Initiate slain' },
      { type: 'collect', itemId: 'emberbound_orders', count: 4, label: 'Emberbound Orders' },
    ],
    xpReward: 5200,
    copperReward: 2400,
    itemRewards: {},
    requiresQuest: 'q_emberbound_scouts',
  },
  q_emberash_study: {
    id: 'q_emberash_study',
    name: 'Cores of the Frontier',
    giverNpcId: 'loremaster_sela',
    turnInNpcId: 'loremaster_sela',
    text: 'The fire has bred creatures of living slag — Magma Husks, lurching out of the Cinderpit. Put down twelve, $N. I would study what the blight makes of stone and flame.',
    completionText: 'Slag that walks. The fire is not merely spreading, $N — it is shaping. I must learn how.',
    objectives: [{ type: 'kill', targetMobId: 'magma_husk', count: 12, label: 'Magma Husk slain' }],
    xpReward: 5600,
    copperReward: 2600,
    itemRewards: {},
    minLevel: 23,
  },
  q_emberash_cores: {
    id: 'q_emberash_cores',
    name: 'What the Slag Remembers',
    giverNpcId: 'loremaster_sela',
    turnInNpcId: 'loremaster_sela',
    text: 'At their heart the Husks carry a cooling slag core — the fire half-remembered in stone. Bring me six. If I can read them, I may learn how to make the whole frontier forget.',
    completionText: 'Six cores, each one a memory of the burning. There is a pattern here, $N. The fire answers to something — or someone.',
    objectives: [{ type: 'collect', itemId: 'cooling_slag_core', count: 6, label: 'Cooling Slag Core' }],
    xpReward: 5700,
    copperReward: 2600,
    itemRewards: {},
    requiresQuest: 'q_emberash_study',
  },
  q_blightash_unrest: {
    id: 'q_blightash_unrest',
    name: 'The Blightash Flats',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'The ash-buried dead of the Flats will not rest, $N — the Emberbound raise them as Blightash Revenants to swell their numbers. Lay twelve back down. The dead of this frontier have suffered enough.',
    completionText: 'Twelve souls returned to the ash. The Emberbound will raise more, but tonight the Flats are quiet.',
    objectives: [{ type: 'kill', targetMobId: 'blightash_revenant', count: 12, label: 'Blightash Revenant slain' }],
    xpReward: 6000,
    copperReward: 2800,
    itemRewards: {},
    minLevel: 23,
  },
  q_blightash_wights: {
    id: 'q_blightash_wights',
    name: 'Ash That Remembers',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'The strongest of the risen dead are Wights — withered things that drain the life from any who near them. Kill six, $N, and bring me the ash-lockets they wear. I would lay the names within to rest.',
    completionText: 'Six names, read and released. Take this — ash-woven, ward-blessed. You have earned a warmer thing than the Flats can give.',
    objectives: [
      { type: 'kill', targetMobId: 'blightash_wight', count: 6, label: 'Blightash Wight slain' },
      { type: 'collect', itemId: 'wight_ash_locket', count: 4, label: 'Wight Ash Locket' },
    ],
    xpReward: 6400,
    copperReward: 3000,
    itemRewards: { warrior: 'boneash_vest', mage: 'cinderwrought_robe', rogue: 'ashveil_jerkin' },
    requiresQuest: 'q_blightash_unrest',
    minLevel: 24,
  },
  q_charwing_eggs: {
    id: 'q_charwing_eggs',
    name: 'Roost Above the Ash',
    giverNpcId: 'scout_brannis',
    turnInNpcId: 'scout_brannis',
    text: 'The Charwing rocs nest on the crags above the Roost, and their brood grows with the fire. Take six eggs from the roost before the flock doubles again, $N.',
    completionText: 'Six eggs cold and unhatched. The flock will not grow this season. Brave work, climbing that roost.',
    objectives: [{ type: 'collect', itemId: 'charwing_egg', count: 6, label: 'Charwing Egg' }],
    xpReward: 6300,
    copperReward: 2900,
    itemRewards: {},
    minLevel: 24,
  },
  q_charwing_matriarch: {
    id: 'q_charwing_matriarch',
    name: 'The Matriarch',
    giverNpcId: 'scout_brannis',
    turnInNpcId: 'scout_brannis',
    text: 'The flock answers to one great old roc — the Matriarch, wings trailing cinder. While she lives the roost will always refill. End her, $N, and bring me a talon. She circles the high Roost.',
    completionText: "The Matriarch's talon, still warm. The roost is broken. Wear this crest — you climbed higher than any of my trackers dared.",
    objectives: [{ type: 'collect', itemId: 'matriarchs_talon', count: 1, label: "Matriarch's Talon" }],
    xpReward: 7000,
    copperReward: 3400,
    itemRewards: { warrior: 'matriarchs_crest_helm', mage: 'matriarchs_crest_helm', rogue: 'matriarchs_crest_helm' },
    requiresQuest: 'q_charwing_eggs',
    minLevel: 25,
  },
  q_slagjaw_raiders: {
    id: 'q_slagjaw_raiders',
    name: 'Raiders of the Hold',
    giverNpcId: 'warden_ulra',
    turnInNpcId: 'warden_ulra',
    text: "The Slagjaw ogres have made a hold of the eastern crags and raid my supply lines for the iron they cannot forge. Break twelve Marauders, $N, and they will think twice before the next raid.",
    completionText: "Twelve marauders broken. The Slagjaw will lick their wounds — but their chieftain still holds the crag.",
    objectives: [{ type: 'kill', targetMobId: 'slagjaw_marauder', count: 12, label: 'Slagjaw Marauder slain' }],
    xpReward: 6200,
    copperReward: 2900,
    itemRewards: {},
    minLevel: 24,
  },
  q_slagjaw_chieftain: {
    id: 'q_slagjaw_chieftain',
    name: "The Chieftain's Hold",
    giverNpcId: 'warden_ulra',
    turnInNpcId: 'warden_ulra',
    text: 'Their chieftain wears a warhelm of slag-iron and works himself into a molten fury when cornered. Take him in his hold at the crag, $N — take a few strong backs with you. With him gone the Slagjaw will scatter for good.',
    completionText: "The Slagjaw warhelm, still hot from his fury. They are scattering already. The east is ours, $N.",
    objectives: [{ type: 'kill', targetMobId: 'slagjaw_chieftain', count: 1, label: 'Slagjaw Chieftain slain' }],
    xpReward: 7400,
    copperReward: 3600,
    itemRewards: { warrior: 'chieftains_maul', mage: 'slagforge_warstaff', rogue: 'slagjaw_skinning_knife' },
    requiresQuest: 'q_slagjaw_raiders',
    minLevel: 25,
    suggestedPlayers: 3,
  },
  q_emberward_signal: {
    id: 'q_emberward_signal',
    name: 'Wisps of the Cinderpit',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'The Cinderpit churns with Ember Wisps now, $N — motes of the living fire, drawn to the rite the Emberbound work below. Snuff ten. Each one we take is a fraction of fuel the cult cannot feed their heart.',
    completionText: 'Ten wisps snuffed. The pit dims, just a little. We are close to their vault now — I can feel the heat of it.',
    objectives: [{ type: 'kill', targetMobId: 'ember_wisp', count: 10, label: 'Ember Wisp slain' }],
    xpReward: 6800,
    copperReward: 3200,
    itemRewards: {},
    minLevel: 25,
  },
  q_emberward_wisps: {
    id: 'q_emberward_wisps',
    name: 'What the Wisps Carry',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'At a wisp’s heart is a core of pure ember-fire. Bring me five, $N. Sela believes that if we understand what feeds the heart, we can starve it.',
    completionText: 'Five cores of living fire. Sela has what she needs. The vault door is just beyond the pit now.',
    objectives: [{ type: 'collect', itemId: 'ember_wisp_core', count: 5, label: 'Ember Wisp Core' }],
    xpReward: 6900,
    copperReward: 3200,
    itemRewards: {},
    requiresQuest: 'q_emberward_signal',
  },
  q_vrask: {
    id: 'q_vrask',
    name: 'The Emberseer',
    giverNpcId: 'loremaster_sela',
    turnInNpcId: 'loremaster_sela',
    text: 'One of the Emberbound has seen too deep into the fire and become its prophet — Vrask the Emberseer, who walks the Cinderpit unburned and mends the cultists with flame. Kill the Emberseer, $N. His staff will tell me how the rite is bound.',
    completionText: "The Emberseer's staff. Now I see how the heart is anchored, $N. We can break it — but only at its source, inside the vault.",
    objectives: [{ type: 'kill', targetMobId: 'vrask_the_emberseer', count: 1, label: 'Vrask the Emberseer slain' }],
    xpReward: 7600,
    copperReward: 3800,
    itemRewards: { warrior: 'emberseer_warblade', mage: 'vrasks_emberstaff', rogue: 'emberseer_fangs' },
    minLevel: 26,
  },
  q_grand_pyrist: {
    id: 'q_grand_pyrist',
    name: 'The Vault Beneath the Ash',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'The Emberbound forge their heart in an old vault, sealed with embers torn from the pit. Gather four vault seal embers from the Cinderpit approach, $N, and we will open the way down into the Emberward Vault.',
    completionText: 'Four seals, and the vault door yields. Beyond it the rite is nearly done. We go down together, $N — and we end this.',
    objectives: [{ type: 'collect', itemId: 'vault_seal_ember', count: 4, label: 'Vault Seal Ember' }],
    xpReward: 7200,
    copperReward: 3600,
    itemRewards: {},
    requiresQuest: 'q_emberward_wisps',
    minLevel: 26,
  },
  q_korzuls_ember: {
    id: 'q_korzuls_ember',
    name: 'The Ember Heart',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: 'Within the vault the rite is led by Grand Pyrist Thessian, who would forge the ember heart and make the blight eternal. Cut him down before the heart is lit, $N. Bring a full band — he does not work the rite alone.',
    completionText: "Thessian falls, but his rite did not fail cleanly — it called something into being below. Steel yourself, $N. The heart has a keeper now.",
    objectives: [{ type: 'kill', targetMobId: 'grand_pyrist_thessian', count: 1, label: 'Grand Pyrist Thessian slain' }],
    xpReward: 8200,
    copperReward: 5000,
    itemRewards: {},
    requiresQuest: 'q_grand_pyrist',
    minLevel: 26,
    suggestedPlayers: 5,
  },
  q_the_emberward_vault: {
    id: 'q_the_emberward_vault',
    name: 'The Emberward Vault',
    giverNpcId: 'brother_aldric_cinderhold',
    turnInNpcId: 'brother_aldric_cinderhold',
    text: "Thessian's rite called a horror of living fire into the vault's heart — Vrothaxis, the Ember Heart made flesh. While it burns the blight will never cool. End it, $N, and seal the vault behind you. This is where the Wyrm's fire dies at last.",
    completionText: 'It is done. The vault is sealed, the heart is cold, and beyond the door the frontier is already cooling. The Wyrm’s fire is out, $N. You carried the Vale’s long road all the way to its end.',
    objectives: [{ type: 'kill', targetMobId: 'vrothaxis_the_ember_heart', count: 1, label: 'Vrothaxis the Ember Heart slain' }],
    xpReward: 9000,
    copperReward: 25000,
    itemRewards: { warrior: 'wyrmash_greatblade', mage: 'staff_of_the_emberward', rogue: 'cinderfang_blades' },
    requiresQuest: 'q_korzuls_ember',
    minLevel: 26,
    suggestedPlayers: 5,
  },
};

export const ZONE4_QUEST_ORDER = [
  'q_cinderhold_signal',
  'q_ashclaw_culling',
  'q_ashclaw_pelts',
  'q_ashclaw_alpha',
  'q_cindermarch_tunnels',
  'q_cinder_resin',
  'q_cindermarch_blasters',
  'q_emberbound_scouts',
  'q_emberbound_orders',
  'q_emberash_study',
  'q_emberash_cores',
  'q_blightash_unrest',
  'q_blightash_wights',
  'q_charwing_eggs',
  'q_charwing_matriarch',
  'q_slagjaw_raiders',
  'q_slagjaw_chieftain',
  'q_emberward_signal',
  'q_emberward_wisps',
  'q_vrask',
  'q_grand_pyrist',
  'q_korzuls_ember',
  'q_the_emberward_vault',
];

// ---------------------------------------------------------------------------
// World layout
// ---------------------------------------------------------------------------

export const ZONE4_CAMPS: CampDef[] = [
  { mobId: 'ashclaw_warg', center: { x: -55, z: 1010 }, radius: 22, count: 7 },
  { mobId: 'ashclaw_warg', center: { x: -30, z: 1025 }, radius: 18, count: 6 },
  { mobId: 'ashclaw_alpha', center: { x: -70, z: 995 }, radius: 4, count: 1 },
  { mobId: 'cindermarch_kobold', center: { x: 70, z: 1030 }, radius: 20, count: 8 },
  { mobId: 'cindermarch_kobold', center: { x: 95, z: 1010 }, radius: 14, count: 6 },
  { mobId: 'cindermarch_blaster', center: { x: 90, z: 1028 }, radius: 6, count: 2 },
  { mobId: 'emberbound_initiate', center: { x: 0, z: 1160 }, radius: 22, count: 8 },
  { mobId: 'emberbound_initiate', center: { x: -25, z: 1180 }, radius: 16, count: 6 },
  { mobId: 'emberbound_pyromancer', center: { x: 15, z: 1170 }, radius: 14, count: 5 },
  { mobId: 'blightash_revenant', center: { x: -40, z: 1120 }, radius: 20, count: 8 },
  { mobId: 'blightash_revenant', center: { x: -65, z: 1100 }, radius: 16, count: 6 },
  { mobId: 'blightash_wight', center: { x: -50, z: 1110 }, radius: 6, count: 1 },
  { mobId: 'charwing_roc', center: { x: 50, z: 1080 }, radius: 18, count: 7 },
  { mobId: 'charwing_matriarch', center: { x: 60, z: 1090 }, radius: 5, count: 1 },
  { mobId: 'slagjaw_marauder', center: { x: 100, z: 1110 }, radius: 20, count: 8 },
  { mobId: 'slagjaw_chieftain', center: { x: 108, z: 1118 }, radius: 3, count: 1 },
  { mobId: 'magma_husk', center: { x: -20, z: 1200 }, radius: 18, count: 7 },
  { mobId: 'ember_wisp', center: { x: -5, z: 1210 }, radius: 14, count: 6 },
  { mobId: 'vrask_the_emberseer', center: { x: -25, z: 1215 }, radius: 5, count: 1 },
];

export const ZONE4_OBJECTS: GroundObjectDef[] = [
  {
    itemId: 'cinderhold_signal_flare',
    name: 'Cinderhold Signal Flare',
    positions: [
      { x: 1, z: 974 },
      { x: -2, z: 977 },
    ],
  },
  {
    itemId: 'cinder_resin',
    name: 'Cinder Resin',
    positions: [
      { x: 64, z: 1022 },
      { x: 71, z: 1018 },
      { x: 78, z: 1025 },
      { x: 84, z: 1032 },
      { x: 90, z: 1020 },
      { x: 96, z: 1014 },
    ],
  },
  {
    itemId: 'cooling_slag_core',
    name: 'Cooling Slag Core',
    positions: [
      { x: -18, z: 1192 },
      { x: -12, z: 1198 },
      { x: -6, z: 1205 },
      { x: 0, z: 1196 },
    ],
  },
  {
    itemId: 'vault_seal_ember',
    name: 'Vault Seal Ember',
    positions: [
      { x: -4, z: 1228 },
      { x: 0, z: 1232 },
      { x: 4, z: 1228 },
      { x: 0, z: 1236 },
    ],
  },
];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const ZONE4_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  cinderhold_signal_flare: { id: 'cinderhold_signal_flare', name: 'Cinderhold Signal Flare', kind: 'quest', sellValue: 0, questId: 'q_cinderhold_signal' },
  ashclaw_pelt: { id: 'ashclaw_pelt', name: 'Ashclaw Pelt', kind: 'quest', sellValue: 0, questId: 'q_ashclaw_pelts' },
  alphas_fang: { id: 'alphas_fang', name: "Alpha's Fang", kind: 'quest', sellValue: 0, questId: 'q_ashclaw_alpha' },
  cinder_resin: { id: 'cinder_resin', name: 'Cinder Resin', kind: 'quest', sellValue: 0, questId: 'q_cinder_resin' },
  emberbound_orders: { id: 'emberbound_orders', name: 'Emberbound Orders', kind: 'quest', sellValue: 0, questId: 'q_emberbound_orders' },
  cooling_slag_core: { id: 'cooling_slag_core', name: 'Cooling Slag Core', kind: 'quest', sellValue: 0, questId: 'q_emberash_cores' },
  wight_ash_locket: { id: 'wight_ash_locket', name: 'Wight Ash Locket', kind: 'quest', sellValue: 0, questId: 'q_blightash_wights' },
  charwing_egg: { id: 'charwing_egg', name: 'Charwing Egg', kind: 'quest', sellValue: 0, questId: 'q_charwing_eggs' },
  matriarchs_talon: { id: 'matriarchs_talon', name: "Matriarch's Talon", kind: 'quest', sellValue: 0, questId: 'q_charwing_matriarch' },
  ember_wisp_core: { id: 'ember_wisp_core', name: 'Ember Wisp Core', kind: 'quest', sellValue: 0, questId: 'q_emberward_wisps' },
  vault_seal_ember: { id: 'vault_seal_ember', name: 'Vault Seal Ember', kind: 'quest', sellValue: 0, questId: 'q_grand_pyrist' },

  // --- quest greens (uncommon) ---
  ashclaw_treads: { id: 'ashclaw_treads', name: 'Ashclaw Treads', kind: 'armor', slot: 'feet', quality: 'uncommon', stats: { armor: 70, agi: 4, sta: 3 }, sellValue: 1100 },
  alphas_fang_mantle: { id: 'alphas_fang_mantle', name: "Alpha's Fang Mantle", kind: 'armor', slot: 'shoulder', quality: 'uncommon', stats: { armor: 85, agi: 6, sta: 3 }, sellValue: 1300 },

  // --- quest blues (rare) ---
  boneash_vest: { id: 'boneash_vest', name: 'Boneash Vest', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 240, sta: 8, str: 4 }, sellValue: 3200, requiredClass: ['warrior'] },
  cinderwrought_robe: { id: 'cinderwrought_robe', name: 'Cinderwrought Robe', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 80, int: 12, spi: 5 }, sellValue: 3200, requiredClass: ['mage'] },
  ashveil_jerkin: { id: 'ashveil_jerkin', name: 'Ashveil Jerkin', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 150, agi: 10, sta: 5 }, sellValue: 3200, requiredClass: ['rogue'] },
  matriarchs_crest_helm: { id: 'matriarchs_crest_helm', name: "Matriarch's Crest Helm", kind: 'armor', slot: 'helmet', quality: 'rare', stats: { armor: 130, agi: 5, sta: 5 }, sellValue: 2600 },
  chieftains_maul: { id: 'chieftains_maul', name: "Chieftain's Maul", kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 28, max: 44, speed: 2.7 }, stats: { str: 8, sta: 4 }, sellValue: 2600, requiredClass: ['warrior'] },
  slagforge_warstaff: { id: 'slagforge_warstaff', name: 'Slagforge Warstaff', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 26, max: 42, speed: 3.0 }, stats: { int: 9, spi: 4 }, sellValue: 2600, requiredClass: ['mage'] },
  slagjaw_skinning_knife: { id: 'slagjaw_skinning_knife', name: 'Slagjaw Skinning Knife', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 16, max: 25, speed: 1.7, dagger: true }, stats: { agi: 9, sta: 3 }, sellValue: 2600, requiredClass: ['rogue'] },
  emberseer_warblade: { id: 'emberseer_warblade', name: 'Emberseer Warblade', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 31, max: 49, speed: 2.6 }, stats: { str: 10, sta: 5 }, sellValue: 3400, requiredClass: ['warrior'] },
  vrasks_emberstaff: { id: 'vrasks_emberstaff', name: "Vrask's Emberstaff", kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 33, max: 53, speed: 3.0 }, stats: { int: 13, spi: 6 }, sellValue: 3400, requiredClass: ['mage'] },
  emberseer_fangs: { id: 'emberseer_fangs', name: 'Emberseer Fangs', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 20, max: 31, speed: 1.7, dagger: true }, stats: { agi: 12, sta: 5 }, sellValue: 3400, requiredClass: ['rogue'] },

  // --- epics (the Emberward Vault) ---
  wyrmash_greatblade: { id: 'wyrmash_greatblade', name: 'Wyrmash Greatblade', kind: 'weapon', slot: 'mainhand', quality: 'epic', weapon: { min: 34, max: 54, speed: 2.6 }, stats: { str: 12, sta: 7 }, sellValue: 9000, requiredClass: ['warrior'] },
  staff_of_the_emberward: { id: 'staff_of_the_emberward', name: 'Staff of the Emberward', kind: 'weapon', slot: 'mainhand', quality: 'epic', weapon: { min: 36, max: 58, speed: 3.0 }, stats: { int: 14, spi: 7 }, sellValue: 9000, requiredClass: ['mage'] },
  cinderfang_blades: { id: 'cinderfang_blades', name: 'Cinderfang Blades', kind: 'weapon', slot: 'mainhand', quality: 'epic', weapon: { min: 22, max: 34, speed: 1.7, dagger: true }, stats: { agi: 13, sta: 6 }, sellValue: 9000, requiredClass: ['rogue'] },

  // --- boss/rare extra drops ---
  slagjaw_warhelm: { id: 'slagjaw_warhelm', name: 'Slagjaw Warhelm', kind: 'armor', slot: 'helmet', quality: 'rare', stats: { armor: 200, sta: 7, str: 4 }, sellValue: 2800, requiredClass: ['warrior'] },

  // --- junk ---
  ash_bound_remains: { id: 'ash_bound_remains', name: 'Ash-Bound Remains', kind: 'junk', quality: 'poor', sellValue: 32 },
  slagjaw_brand: { id: 'slagjaw_brand', name: 'Slagjaw Brand', kind: 'quest', sellValue: 0, questId: 'q_slagjaw_raiders' },

  // --- vendor whites: food/drink (Quartermaster Dessa), sized to ~L26 pools ---
  cinderhold_hardbread: { id: 'cinderhold_hardbread', name: 'Cinderhold Hardbread', kind: 'food', foodHp: 680, sellValue: 90, buyValue: 1500 },
  cinderwater_flask: { id: 'cinderwater_flask', name: 'Cinderwater Flask', kind: 'drink', drinkMana: 820, sellValue: 90, buyValue: 1500 },
  slagmere_broth: { id: 'slagmere_broth', name: 'Slagmere Broth', kind: 'food', foodHp: 1040, sellValue: 180, buyValue: 3000 },
  ashveil_cider: { id: 'ashveil_cider', name: 'Ashveil Cider', kind: 'drink', drinkMana: 1080, sellValue: 180, buyValue: 3000 },

  // --- vendor whites: gear (Dessa armor, Kovan weapons) ---
  cinderhold_warblade: { id: 'cinderhold_warblade', name: 'Cinderhold Warblade', kind: 'weapon', slot: 'mainhand', quality: 'common', weapon: { min: 18, max: 28, speed: 2.3 }, sellValue: 750, buyValue: 7500 },
  slagforge_staff: { id: 'slagforge_staff', name: 'Slagforge Staff', kind: 'weapon', slot: 'mainhand', quality: 'common', weapon: { min: 19, max: 31, speed: 3.0 }, stats: { int: 2 }, sellValue: 750, buyValue: 7500 },
  ashfall_dirk: { id: 'ashfall_dirk', name: 'Ashfall Dirk', kind: 'weapon', slot: 'mainhand', quality: 'common', weapon: { min: 12, max: 19, speed: 1.8, dagger: true }, sellValue: 750, buyValue: 7500 },
  cinderhold_breastplate: { id: 'cinderhold_breastplate', name: 'Cinderhold Breastplate', kind: 'armor', slot: 'chest', quality: 'common', stats: { armor: 190 }, sellValue: 850, buyValue: 8500 },
  ashveil_robe: { id: 'ashveil_robe', name: 'Ashveil Robe', kind: 'armor', slot: 'chest', quality: 'common', stats: { armor: 60 }, sellValue: 600, buyValue: 6000 },
  cinderscale_jerkin: { id: 'cinderscale_jerkin', name: 'Cinderscale Jerkin', kind: 'armor', slot: 'chest', quality: 'common', stats: { armor: 115 }, sellValue: 700, buyValue: 7000 },
  slagtread_boots: { id: 'slagtread_boots', name: 'Slagtread Boots', kind: 'armor', slot: 'feet', quality: 'common', stats: { armor: 65 }, sellValue: 500, buyValue: 5000 },
  emberward_leggings: { id: 'emberward_leggings', name: 'Emberward Leggings', kind: 'armor', slot: 'legs', quality: 'common', stats: { armor: 85 }, sellValue: 550, buyValue: 5500 },
};

// ---------------------------------------------------------------------------
// Decorative props (Cinderhold hub + camp dressing)
// ---------------------------------------------------------------------------

export const ZONE4_PROPS: ZonePropsDef = {
  buildings: [
    { kind: 'house', x: 14, z: 991, w: 7, d: 6, rot: -0.5 },
    { kind: 'house', x: 8, z: 970, w: 6, d: 5, rot: 0.4 },
    { kind: 'inn', x: -15, z: 986, w: 6, d: 7, rot: 0.6 },
    { kind: 'chapel', x: -16, z: 970, w: 5, d: 7, rot: 0.9 },
  ],
  wells: [{ x: 0, z: 982, r: 1.5 }],
  stalls: [
    { x: -7.5, z: 987, rot: Math.PI / 2, r: 1.7 }, // Quartermaster Dessa
    { x: -4.5, z: 993.5, rot: -0.6, r: 1.7 }, // Armorer Kovan
  ],
  mines: [
    { x: 80, z: 1034, rot: -2.0 }, // Cindermarch Tunnels
  ],
  docks: [],
  tents: [
    { x: -4, z: 1156, rot: 0.8, scale: 1 }, // Emberbound Camp
    { x: 6, z: 1164, rot: -0.5, scale: 1 },
    { x: -12, z: 1168, rot: 2.2, scale: 1 },
    { x: 102, z: 1106, rot: 0.5, scale: 1.3 }, // Slagjaw's Hold
    { x: 110, z: 1116, rot: 2.0, scale: 1.3 },
  ],
  crates: [
    [100, 1104],
    [106, 1110],
    [-6, 1158],
  ],
  campfires: [
    [2, 978],
    [0, 1160],
    [104, 1110],
  ],
  mudHuts: [],
  ruinRings: [],
  fences: [],
  graveyards: [],
};
